# Generated by Django 5.0.14 on 2025-12-08 10:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última Modificación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro ha sido eliminado lógicamente', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal', primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('days', models.PositiveIntegerField(default=0, verbose_name='Días')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento Pronto Pago (%)')),
                ('discount_days', models.PositiveIntegerField(default=0, verbose_name='Días para Descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la eliminación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la última modificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Término de Pago',
                'verbose_name_plural': 'Términos de Pago',
                'db_table': 'finance_payment_terms',
                'ordering': ['days', 'name'],
            },
        ),
    ]
