# Generated by Django 5.0.14 on 2025-12-08 10:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última Modificación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre identificador del rol (ej. "Gerente de Ventas")', max_length=100, unique=True, verbose_name='Nombre del Rol')),
                ('code', models.CharField(help_text='Código corto para uso en código (ej. "sales_manager")', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción de las responsabilidades y permisos del rol', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el rol puede ser asignado a usuarios', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'auth_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Última Modificación')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro ha sido eliminado lógicamente', verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True, verbose_name='Fecha de Eliminación')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('email', models.EmailField(help_text='Email único para inicio de sesión', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('employee_code', models.CharField(blank=True, help_text='Código único de empleado para vincular con módulo RRHH', max_length=20, null=True, unique=True, verbose_name='Código de Empleado')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Apellido(s)')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono para contacto', max_length=20, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede iniciar sesión', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si puede acceder al admin de Django', verbose_name='Staff')),
                ('language', models.CharField(default='es', help_text='Código de idioma preferido (es, en, etc.)', max_length=10, verbose_name='Idioma')),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=50, verbose_name='Zona Horaria')),
                ('email_notifications', models.BooleanField(default=True, help_text='Recibir notificaciones por correo electrónico', verbose_name='Notificaciones Email')),
                ('push_notifications', models.BooleanField(default=True, help_text='Recibir notificaciones push en móvil', verbose_name='Notificaciones Push')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Cambio de Contraseña')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Intentos Fallidos')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Fecha hasta la cual la cuenta está temporalmente bloqueada', null=True, verbose_name='Bloqueado Hasta')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Usuario que realizó la eliminación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='Rol que define los permisos del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_jti', models.CharField(help_text='Identificador único del refresh token para invalidación', max_length=255, unique=True, verbose_name='JTI del Refresh Token')),
                ('device_type', models.CharField(help_text='web, ios, android', max_length=50, verbose_name='Tipo de Dispositivo')),
                ('device_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Dispositivo')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Inicio de Sesión')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'db_table': 'auth_user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventario'), ('sales', 'Ventas'), ('purchases', 'Compras'), ('finance', 'Finanzas'), ('hr', 'Recursos Humanos'), ('reports', 'Reportes'), ('settings', 'Configuración'), ('users', 'Usuarios')], max_length=50, verbose_name='Módulo')),
                ('action', models.CharField(choices=[('view', 'Ver'), ('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('export', 'Exportar'), ('import', 'Importar'), ('approve', 'Aprobar')], max_length=50, verbose_name='Acción')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='authentication.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulo',
                'db_table': 'auth_module_permissions',
                'ordering': ['role', 'module', 'action'],
                'unique_together': {('role', 'module', 'action')},
            },
        ),
    ]
